import { test, expect, type APIRequestContext } from "@playwright/test";
import { randomUUID } from "node:crypto";

async function token(request: APIRequestContext) {
  const csrf = await (await request.get("/api/auth/csrf")).json();
  return { [csrf.headerName]: csrf.token };
}
async function register(request: APIRequestContext) {
  const account = {
    email: `unison-e2e-${randomUUID()}@example.test`,
    password: "Test-only-password-2026",
    displayName: "Test Musician",
  };
  expect(
    (
      await request.post("/api/auth/register", {
        headers: await token(request),
        data: account,
      })
    ).status(),
  ).toBe(201);
  expect(
    (
      await request.post("/api/auth/login", {
        headers: await token(request),
        form: { email: account.email, password: account.password },
      })
    ).status(),
  ).toBe(204);
}
// Original generated sine wave; no third-party recording or fixture download.
function wave() {
  const samples = 44100 * 4;
  const data = Buffer.alloc(44 + samples * 2);
  data.write("RIFF");
  data.writeUInt32LE(data.length - 8, 4);
  data.write("WAVEfmt ", 8);
  data.writeUInt32LE(16, 16);
  data.writeUInt16LE(1, 20);
  data.writeUInt16LE(1, 22);
  data.writeUInt32LE(44100, 24);
  data.writeUInt32LE(88200, 28);
  data.writeUInt16LE(2, 32);
  data.writeUInt16LE(16, 34);
  data.write("data", 36);
  data.writeUInt32LE(samples * 2, 40);
  for (let i = 0; i < samples; i++)
    data.writeInt16LE(
      Math.round(2000 * Math.sin((2 * Math.PI * 440 * i) / 44100)),
      44 + i * 2,
    );
  return data;
}
async function submit(
  request: APIRequestContext,
  title: string,
  options: {
    buffer?: Buffer;
    name?: string;
    rightsConfirmed?: boolean;
    csrf?: boolean;
  } = {},
) {
  return request.post("/api/uploads", {
    headers: options.csrf === false ? {} : await token(request),
    multipart: {
      metadata: {
        name: "metadata.json",
        mimeType: "application/json",
        buffer: Buffer.from(
          JSON.stringify({
            title,
            artist: "Generated Test Artist",
            genre: "Electronic",
            rightsConfirmed: options.rightsConfirmed ?? true,
            rightsNote:
              "Original sine wave generated by the Unison automated test.",
          }),
        ),
      },
      audio: {
        name: options.name ?? "generated.wav",
        mimeType: "audio/wav",
        buffer: options.buffer ?? wave(),
      },
    },
  });
}
async function status(request: APIRequestContext, id: string) {
  return (await (await request.get(`/api/uploads/${id}`)).json()).status;
}
async function remove(request: APIRequestContext, id: string) {
  expect(
    (
      await request.delete(`/api/uploads/${id}`, {
        headers: await token(request),
      })
    ).status(),
  ).toBe(204);
  await expect
    .poll(async () => (await request.get(`/api/uploads/${id}`)).status(), {
      timeout: 30000,
    })
    .toBe(404);
}

test("upload UI publishes generated audio, streams it, and removes its catalog and library entries", async ({
  page,
}, testInfo) => {
  test.setTimeout(90000);
  await register(page.request);
  const title = `Generated ${randomUUID()}`;
  await page.goto("/uploads");
  await expect(page.getByText("Your first release starts here.")).toBeVisible();
  await page.getByLabel("Audio file", { exact: true }).setInputFiles({
    name: "generated.wav",
    mimeType: "audio/wav",
    buffer: wave(),
  });
  await page.getByLabel("Track title", { exact: true }).fill(title);
  await page
    .getByLabel("Artist name", { exact: true })
    .fill("Generated Test Artist");
  await page
    .getByLabel("Audio source and permission", { exact: true })
    .fill("Original sine wave generated by Unison tests.");
  await page.getByLabel("I created this audio", { exact: false }).check();
  await page
    .getByLabel("Public credits (optional)", { exact: true })
    .fill("Generated by Unison automated tests. MIT license.");
  await page
    .getByRole("button", { name: "Upload and process", exact: true })
    .click();
  await expect(
    page.getByText("Upload received. Follow its progress below."),
  ).toBeVisible();
  await expect(page.locator(".job-status")).toHaveText("Published", {
    timeout: 60000,
  });
  const [job] = await (await page.request.get("/api/uploads")).json();
  const [track] = await (
    await page.request.get(`/api/tracks?q=${encodeURIComponent(title)}`)
  ).json();
  expect(track.id).toBe(job.id);
  expect(track.publicCredits).toBe(
    "Generated by Unison automated tests. MIT license.",
  );
  expect(track.rightsNote).toBeUndefined();
  await page.getByText("Edit public credits", { exact: true }).click();
  await page
    .getByLabel(`Public credits for ${title}`, { exact: true })
    .fill("Updated public credits: Unison tests, MIT.");
  await page.getByRole("button", { name: "Save credits", exact: true }).click();
  await expect(
    page.getByText("Public credits saved.", { exact: true }),
  ).toBeVisible();
  expect(track.durationSeconds).toBeGreaterThanOrEqual(4);
  const playlistResponse = await page.request.post("/api/library/playlists", {
    headers: await token(page.request),
    data: { name: "Upload lifecycle", description: "Generated test audio" },
  });
  expect(playlistResponse.status()).toBe(201);
  const playlist = await playlistResponse.json();
  expect(
    (
      await page.request.put(
        `/api/library/playlists/${playlist.id}/tracks/${job.id}`,
        { headers: await token(page.request) },
      )
    ).status(),
  ).toBe(204);
  const media = await page.request.get(track.audioUrl, {
    headers: { Range: "bytes=0-127" },
  });
  expect(media.status()).toBe(206);
  expect(media.headers()["content-type"]).toContain("audio/mpeg");
  expect((await page.request.get(`/media/originals/${job.id}`)).status()).toBe(
    403,
  );
  await page.screenshot({
    path: testInfo.outputPath("uploads-published.png"),
    fullPage: true,
  });
  expect(
    await page.evaluate(
      () => document.documentElement.scrollWidth <= innerWidth,
    ),
  ).toBe(true);
  await page
    .getByRole("link", { name: "Find in Discover", exact: false })
    .click();
  await page
    .getByRole("button", { name: `Credits for ${title}`, exact: true })
    .click();
  await expect(page.getByRole("dialog")).toContainText(
    "Updated public credits: Unison tests, MIT.",
  );
  await page
    .getByRole("button", { name: "Close credits", exact: true })
    .click();
  await page
    .getByRole("button", { name: `Play ${title}`, exact: true })
    .click();
  await expect
    .poll(() =>
      page
        .locator("audio")
        .evaluate((audio: HTMLAudioElement) => audio.currentTime),
    )
    .toBeGreaterThan(0.2);
  await page
    .getByRole("button", { name: `Save ${title} to favorites`, exact: true })
    .click();
  await expect(
    page.getByRole("button", {
      name: `Remove ${title} from favorites`,
      exact: true,
    }),
  ).toBeVisible();
  await page.getByRole("link", { name: "Upload audio", exact: true }).click();
  await page
    .getByRole("button", { name: `Remove upload ${title}`, exact: true })
    .click();
  await page
    .getByRole("button", { name: "Remove permanently", exact: true })
    .click();
  await expect(page.getByText("Your first release starts here.")).toBeVisible({
    timeout: 30000,
  });
  expect(
    await (
      await page.request.get(`/api/tracks?q=${encodeURIComponent(title)}`)
    ).json(),
  ).toEqual([]);
  expect(
    await (await page.request.get("/api/library/favorites")).json(),
  ).toEqual([]);
  expect(
    (
      await (
        await page.request.get(`/api/library/playlists/${playlist.id}`)
      ).json()
    ).tracks,
  ).toEqual([]);
  await expect
    .poll(async () => (await page.request.get(track.audioUrl)).status())
    .toBe(404);
});

test("upload authorization, validation, failure and retry preserve private ownership", async ({
  request,
  playwright,
}) => {
  test.setTimeout(90000);
  expect((await request.get("/api/uploads")).status()).toBe(401);
  await register(request);
  const title = `Invalid ${randomUUID()}`;
  expect((await submit(request, title, { csrf: false })).status()).toBe(403);
  expect(
    (await submit(request, title, { rightsConfirmed: false })).status(),
  ).toBe(400);
  expect(
    (await submit(request, title, { name: "generated.exe" })).status(),
  ).toBe(400);
  expect(
    (await submit(request, title, { buffer: Buffer.alloc(0) })).status(),
  ).toBe(400);
  expect(
    (
      await submit(request, title, {
        buffer: Buffer.alloc(25 * 1024 * 1024 + 1),
      })
    ).status(),
  ).toBe(413);
  expect((await request.get(`/api/tracks?q=${"x".repeat(121)}`)).status()).toBe(
    400,
  );
  const response = await submit(request, title, {
    buffer: Buffer.from("not an audio file"),
  });
  expect(response.status()).toBe(202);
  const job = await response.json();
  await expect
    .poll(() => status(request, job.id), { timeout: 30000 })
    .toBe("FAILED");
  expect(
    (await (await request.get(`/api/uploads/${job.id}`)).json()).error,
  ).toContain("could not be decoded");
  expect(
    await (
      await request.get(`/api/tracks?q=${encodeURIComponent(title)}`)
    ).json(),
  ).toEqual([]);
  const other = await playwright.request.newContext({
    baseURL: process.env.UNISON_URL ?? "http://localhost:3000",
  });
  try {
    await register(other);
    expect(await (await other.get("/api/uploads")).json()).toEqual([]);
    expect((await other.get(`/api/uploads/${job.id}`)).status()).toBe(404);
    expect(
      (
        await other.put(`/api/uploads/${job.id}/credits`, {
          headers: await token(other),
          data: { publicCredits: "Not mine" },
        })
      ).status(),
    ).toBe(404);
    expect(
      (
        await request.put(`/api/uploads/${job.id}/credits`, {
          data: { publicCredits: "Missing CSRF" },
        })
      ).status(),
    ).toBe(403);
    expect(
      (
        await request.put(`/api/uploads/${job.id}/credits`, {
          headers: await token(request),
          data: { publicCredits: "x".repeat(1001) },
        })
      ).status(),
    ).toBe(400);
    expect(
      (
        await other.delete(`/api/uploads/${job.id}`, {
          headers: await token(other),
        })
      ).status(),
    ).toBe(404);
    expect(
      (
        await other.post(`/api/uploads/${job.id}/retry`, {
          headers: await token(other),
        })
      ).status(),
    ).toBe(404);
  } finally {
    await other.dispose();
  }
  expect(
    (
      await request.post(`/api/uploads/${job.id}/retry`, {
        headers: await token(request),
      })
    ).status(),
  ).toBe(204);
  await expect
    .poll(() => status(request, job.id), { timeout: 30000 })
    .toBe("FAILED");
  await remove(request, job.id);
});
